### ISSUE TITLE
 运行sample报错

### ISSUE THREAD

**Issue by btfak** [alanyang/dhtspider#2]
报错内容

```
const {Table, Node} = require('./table')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/long/gopath/src/github.com/alanyang/dhtspider/sample/index.js:3:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

```
执行命令 ：node index.js
```

node版本

```
node --version
v5.9.1
```

**Comment by btfak** [comment]
更新node到6.2解决了
