### ISSUE TITLE
does not work.

### ISSUE THREAD

**Issue by Zibri** [alanyang/dhtspider#6]
if I start the sample I get:

lib/spider.js:6
const {Table, Node} = require('./table')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/zibri/dhtspider/sample/index.js:3:21)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by alanyang** [comment]
node.js 6.0+ supported
